language: node_js

node_js:
  - '10'

cache: npm

script:
  - npm run build

before_deploy:
  - npm run build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: storybook-static
  on:
    branch: master
